### ISSUE TITLE
RSS feed is invalid because it does not contain a mail address

### ISSUE THREAD

**Issue by ottlinger** [rundeck/rundeck-ghpages#3]
Verifying the RSS feed yields an error:
http://www.feedvalidator.org/check?url=http://rundeck.org/news/feed.xml
because the field author is supposed to contain a mail address.

Is there a mailing list that could be used instead of the project name?

```
<author>Rundeck Project</author>
```

**Comment by gschueler** [comment]
thanks, i think i've fixed it now.

**Comment by ottlinger** [comment]
Thanks :-)
